version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10
    working_directory: ~/app

  restore_cache: &restore_cache
    restore_cache:
      name: Restore Yarn package cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}

  save_cache: &save_cache
    save_cache:
      name: Save Yarn package cache
      key: yarn-packages-v1-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

  install_deps: &install_deps
    run:
      name: Install dependencies
      command: yarn

jobs:
  test:
    <<: *container_config
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      -
        run:
          name: Lint the code
          command: yarn lint
#      -
#        run:
#          name: Jest suite
#          command: yarn test
#          environment:
#            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
#      -
#        store_test_results:
#          path: packages/client/reports
#      -
#        store_artifacts:
#          path: packages/client/coverage
  deploy:
    <<: *container_config
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      -
        run:
          name: Deploy to now.sh
          command: |
            yarn deploy:production

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
